ATLANTA_REGION = [
    # Inside the perimeter (ITP)
    "Atlanta, GA",
    "Brookhaven, GA",
    "Decatur, GA",
    "Druid Hills, GA",
    "East Point, GA",
    "Hapeville, GA",
    "College Park, GA",
    "North Druid Hills, GA",
    "West End, GA",
    "Virginia-Highland, GA",
    "Grant Park, GA",
    "Old Fourth Ward, GA",
    "Candler Park, GA",
    
    # Outside the perimeter (OTP)
    "Alpharetta, GA",
    "Roswell, GA",
    "Sandy Springs, GA",
    "Marietta, GA",
    "Smyrna, GA",
    "Duluth, GA",
    "Norcross, GA",
    "Lawrenceville, GA",
    "Snellville, GA",
    "Lithonia, GA",
    "Stone Mountain, GA",
    "Tucker, GA",
    "Peachtree Corners, GA",
    "Johns Creek, GA",
    "Suwanee, GA",
    "Dunwoody, GA",
    "Chamblee, GA",
    "Woodstock, GA",
    "Kennesaw, GA",
    "Acworth, GA",
    "Powder Springs, GA",
    "Austell, GA",
    "Mableton, GA",
    "Fairburn, GA",
    "Union City, GA",
    "Douglasville, GA",
    "McDonough, GA",
    "Stockbridge, GA",
    "Conyers, GA",
    "Covington, GA"
]

MIAMI_REGION = [
    # Central Miami (Inside)
    "Miami, FL",
    "Miami Beach, FL",
    "Coral Gables, FL",
    "Coconut Grove, FL",
    "Little Havana, FL",
    "Wynwood, FL",
    "Allapattah, FL",
    "Brickell, FL",
    "Overtown, FL",
    "Edgewater, FL",
    "Midtown Miami, FL",
    "Design District, FL",
    "Key Biscayne, FL",
    "North Bay Village, FL",
    
    # Surrounding Areas (Outside)
    "Hialeah, FL",
    "North Miami, FL",
    "North Miami Beach, FL",
    "Miami Gardens, FL",
    "Aventura, FL",
    "Sunny Isles Beach, FL",
    "Surfside, FL",
    "Bal Harbour, FL",
    "Doral, FL",
    "Kendall, FL",
    "South Miami, FL",
    "Palmetto Bay, FL",
    "Cutler Bay, FL",
    "Homestead, FL",
    "Pinecrest, FL",
    "Miami Lakes, FL",
    "Medley, FL",
    "West Miami, FL",
    "Sweetwater, FL",
    "Miami Springs, FL",
    "Virginia Gardens, FL",
    "Opa-locka, FL",
    "Hallandale Beach, FL",
    "Hollywood, FL",
    "Pembroke Pines, FL",
    "Miramar, FL",
    "Davie, FL",
    "Fort Lauderdale, FL"
]

TAMPA_REGION = [
    # Central Tampa (Inside)
    "Tampa, FL",
    "Ybor City, FL",
    "Hyde Park, FL",
    "Downtown Tampa, FL",
    "Channel District, FL",
    "Westshore, FL",
    "Seminole Heights, FL",
    "South Tampa, FL",
    "Davis Islands, FL",
    "Harbour Island, FL",
    "Palma Ceia, FL",

    # Surrounding Areas (Outside)
    "St. Petersburg, FL",
    "Clearwater, FL",
    "Brandon, FL",
    "Riverview, FL",
    "Lutz, FL",
    "Wesley Chapel, FL",
    "New Tampa, FL",
    "Temple Terrace, FL",
    "Plant City, FL",
    "Town 'n' Country, FL",
    "Carrollwood, FL",
    "Apollo Beach, FL",
    "Sun City Center, FL",
    "Seffner, FL",
    "Valrico, FL",
    "Oldsmar, FL",
    "Safety Harbor, FL",
    "Dunedin, FL",
    "Largo, FL",
    "Pinellas Park, FL",
    "Tarpon Springs, FL",
    "Palm Harbor, FL",
    "Odessa, FL",
    "Trinity, FL",
    "Gulfport, FL",
    "Madeira Beach, FL",
    "Treasure Island, FL",
    "Redington Beach, FL",
    "Indian Rocks Beach, FL",
    "Clearwater Beach, FL"
]

HOUSTON_REGION = [
    # Central Houston (Inside)
    "Houston, TX",
    "Midtown, TX",
    "Downtown Houston, TX",
    "The Heights, TX",
    "Montrose, TX",
    "Museum District, TX",
    "Medical Center, TX",
    "West University Place, TX",
    "Bellaire, TX",
    "River Oaks, TX",
    "Galleria/Uptown, TX",
    "Memorial Park, TX",
    "EaDo (East Downtown), TX",
    "Third Ward, TX",
    "Fourth Ward, TX",
    "Greenway Plaza, TX",

    # Surrounding Areas (Outside)
    "Sugar Land, TX",
    "Katy, TX",
    "Pearland, TX",
    "Pasadena, TX",
    "League City, TX",
    "Friendswood, TX",
    "The Woodlands, TX",
    "Conroe, TX",
    "Spring, TX",
    "Kingwood, TX",
    "Cypress, TX",
    "Tomball, TX",
    "Missouri City, TX",
    "Richmond, TX",
    "Rosenberg, TX",
    "Baytown, TX",
    "Channelview, TX",
    "Deer Park, TX",
    "Humble, TX",
    "Atascocita, TX",
    "Clear Lake, TX",
    "Webster, TX",
    "Seabrook, TX",
    "La Porte, TX",
    "Alvin, TX",
    "Manvel, TX",
    "Fulshear, TX",
    "Stafford, TX",
    "Galena Park, TX",
    "South Houston, TX",
    "Brookshire, TX",
    "Santa Fe, TX",
    "Jacinto City, TX"
]

COLUMBUS_REGION = [
    # Central Columbus (Inside)
    "Columbus, OH",
    "Downtown Columbus, OH",
    "Short North, OH",
    "German Village, OH",
    "Arena District, OH",
    "University District, OH",
    "Clintonville, OH",
    "Bexley, OH",
    "Grandview Heights, OH",
    "Franklinton, OH",
    "Italian Village, OH",
    "Victorian Village, OH",
    "Olde Towne East, OH",
    "Merion Village, OH",
    "Hilltop, OH",
    "Linden, OH",

    # Surrounding Areas (Outside)
    "Dublin, OH",
    "Westerville, OH",
    "Gahanna, OH",
    "Hilliard, OH",
    "Reynoldsburg, OH",
    "Upper Arlington, OH",
    "Worthington, OH",
    "Grove City, OH",
    "Canal Winchester, OH",
    "Pickerington, OH",
    "New Albany, OH",
    "Powell, OH",
    "Lewis Center, OH",
    "Blacklick, OH",
    "Sunbury, OH",
    "Pataskala, OH",
    "Whitehall, OH",
    "Obetz, OH",
    "Groveport, OH",
    "Plain City, OH",
    "Delaware, OH",
    "Marysville, OH",
    "Lancaster, OH",
    "Circleville, OH",
    "Heath, OH",
    "Johnstown, OH",
    "Granville, OH",
    "Hebron, OH"
]

CHICAGO_REGION = [
    # Central Chicago (Inside)
    "Chicago, IL",
    "The Loop, IL",
    "River North, IL",
    "West Loop, IL",
    "Lincoln Park, IL",
    "Lakeview, IL",
    "Wicker Park, IL",
    "Logan Square, IL",
    "Hyde Park, IL",
    "Old Town, IL",
    "Gold Coast, IL",
    "Streeterville, IL",
    "South Loop, IL",
    "Chinatown, IL",
    "Pilsen, IL",
    "Bridgeport, IL",
    "Uptown, IL",
    "Edgewater, IL",
    "Rogers Park, IL",
    "Andersonville, IL",
    "Bronzeville, IL",
    "Little Village, IL",
    "Avondale, IL",
    "Bucktown, IL",
    "Humboldt Park, IL",
    "West Town, IL",

    # Surrounding Areas (Outside)
    "Evanston, IL",
    "Skokie, IL",
    "Oak Park, IL",
    "Cicero, IL",
    "Berwyn, IL",
    "Oak Lawn, IL",
    "Des Plaines, IL",
    "Niles, IL",
    "Park Ridge, IL",
    "Elmwood Park, IL",
    "River Forest, IL",
    "Forest Park, IL",
    "La Grange, IL",
    "Wilmette, IL",
    "Glenview, IL",
    "Northbrook, IL",
    "Highland Park, IL",
    "Schaumburg, IL",
    "Naperville, IL",
    "Aurora, IL",
    "Downers Grove, IL",
    "Orland Park, IL",
    "Tinley Park, IL",
    "Bolingbrook, IL",
    "Joliet, IL",
    "Wheaton, IL",
    "Elgin, IL",
    "Arlington Heights, IL",
    "Palatine, IL",
    "Buffalo Grove, IL",
    "Libertyville, IL",
    "Vernon Hills, IL",
    "Mundelein, IL",
    "Lake Forest, IL",
    "Hoffman Estates, IL",
    "Mount Prospect, IL",
    "Gurnee, IL"
]

MANHATTAN_REGION = [
    # Central Manhattan (Neighborhoods/Areas)
    "Lower Manhattan, NY",
    "Financial District, NY",
    "Battery Park City, NY",
    "Tribeca, NY",
    "SoHo, NY",
    "Chinatown, NY",
    "Little Italy, NY",
    "Nolita, NY",
    "Greenwich Village, NY",
    "East Village, NY",
    "West Village, NY",
    "Chelsea, NY",
    "Flatiron District, NY",
    "Gramercy, NY",
    "NoMad, NY",
    "Union Square, NY",
    "Midtown, NY",
    "Theater District, NY",
    "Hell's Kitchen, NY",
    "Times Square, NY",
    "Garment District, NY",
    "Murray Hill, NY",
    "Kips Bay, NY",
    "Upper East Side, NY",
    "Upper West Side, NY",
    "Central Park, NY",
    "Harlem, NY",
    "East Harlem, NY",
    "Hamilton Heights, NY",
    "Washington Heights, NY",
    "Inwood, NY",
    "Lenox Hill, NY",
    "Yorkville, NY",
    "Morningside Heights, NY",
    "Battery Park, NY",
    "Hudson Yards, NY",
    "Two Bridges, NY",
    "Stuyvesant Town, NY",
    "Roosevelt Island, NY"
]

BROOKLYN_REGION = [
    # Central Brooklyn (Neighborhoods/Areas)
    "Brooklyn Heights, NY",
    "DUMBO, NY",
    "Downtown Brooklyn, NY",
    "Williamsburg, NY",
    "Greenpoint, NY",
    "Bushwick, NY",
    "Bedford-Stuyvesant, NY",
    "Fort Greene, NY",
    "Clinton Hill, NY",
    "Prospect Heights, NY",
    "Park Slope, NY",
    "Gowanus, NY",
    "Carroll Gardens, NY",
    "Red Hook, NY",
    "Cobble Hill, NY",
    "Boerum Hill, NY",
    "Crown Heights, NY",
    "Flatbush, NY",
    "Ditmas Park, NY",
    "Kensington, NY",
    "Midwood, NY",
    "Prospect Lefferts Gardens, NY",
    "Sunset Park, NY",
    "Bay Ridge, NY",
    "Borough Park, NY",
    "Sheepshead Bay, NY",
    "Brighton Beach, NY",
    "Coney Island, NY",
    "Gravesend, NY",
    "Marine Park, NY",
    "Canarsie, NY",
    "Brownsville, NY",
    "East New York, NY",
    "Bush Terminal, NY",
    "Windsor Terrace, NY",
    "Mill Basin, NY",
    "Bensonhurst, NY",
    "Dyker Heights, NY",
    "Flatlands, NY"
]

BRONX_REGION = [
    # Central Bronx (Neighborhoods/Areas)
    "Fordham, NY",
    "Bedford Park, NY",
    "Belmont, NY",
    "Kingsbridge, NY",
    "Riverdale, NY",
    "University Heights, NY",
    "Norwood, NY",
    "Woodlawn, NY",
    "Van Cortlandt Village, NY",
    "Wakefield, NY",
    "Pelham Parkway, NY",
    "Morris Park, NY",
    "Throgs Neck, NY",
    "Soundview, NY",
    "Westchester Square, NY",
    "Pelham Bay, NY",
    "Parkchester, NY",
    "Castle Hill, NY",
    "Country Club, NY",
    "City Island, NY",
    "Hunts Point, NY",
    "Mott Haven, NY",
    "Melrose, NY",
    "Concourse, NY",
    "Highbridge, NY",
    "Tremont, NY",
    "Mount Eden, NY",
    "Mount Hope, NY",
    "Williamsbridge, NY",
    "Baychester, NY",
    "Co-op City, NY",
    "Allerton, NY",
    "Bronxwood, NY",
    "Edenwald, NY",
    "Eastchester, NY"
]

HARLEM_REGION = [
    # Central Harlem and Surrounding Areas
    "Central Harlem, NY",
    "West Harlem, NY",
    "East Harlem (El Barrio), NY",
    "Hamilton Heights, NY",
    "Sugar Hill, NY",
    "Manhattanville, NY",
    "Morningside Heights, NY"
]

CLEVELAND_REGION = [
    # Central Cleveland (Neighborhoods)
    "Downtown Cleveland, OH",
    "Ohio City, OH",
    "Tremont, OH",
    "Detroit-Shoreway, OH",
    "University Circle, OH",
    "Glenville, OH",
    "Collinwood, OH",
    "Fairfax, OH",
    "Hough, OH",
    "Old Brooklyn, OH",
    "West Park, OH",
    "Kamm's Corners, OH",
    "Edgewater, OH",
    "Clark-Fulton, OH",
    "Slavic Village, OH",
    "Broadway, OH",
    "Lee-Harvard, OH",
    "Mount Pleasant, OH",
    "Buckeye-Shaker Square, OH",
    "Little Italy, OH",
    "North Collinwood, OH",
    "South Collinwood, OH",

    # Surrounding Areas
    "Lakewood, OH",
    "Parma, OH",
    "Cleveland Heights, OH",
    "Shaker Heights, OH",
    "Euclid, OH",
    "Garfield Heights, OH",
    "Maple Heights, OH",
    "Brooklyn, OH",
    "Bedford, OH",
    "Bedford Heights, OH",
    "East Cleveland, OH",
    "Strongsville, OH",
    "Westlake, OH",
    "North Olmsted, OH",
    "Rocky River, OH",
    "Fairview Park, OH",
    "Berea, OH",
    "Bay Village, OH",
    "South Euclid, OH",
    "Lyndhurst, OH",
    "Mayfield Heights, OH",
    "Beachwood, OH",
    "Solon, OH",
    "Chagrin Falls, OH",
    "Brecksville, OH",
    "Independence, OH"
]

DETROIT_REGION = [
    # Central Detroit (Neighborhoods)
    "Downtown Detroit, MI",
    "Midtown, MI",
    "Corktown, MI",
    "Greektown, MI",
    "Eastern Market, MI",
    "Brush Park, MI",
    "Lafayette Park, MI",
    "New Center, MI",
    "Woodbridge, MI",
    "West Village, MI",
    "Indian Village, MI",
    "Boston-Edison, MI",
    "University District, MI",
    "Palmer Woods, MI",
    "Rosedale Park, MI",
    "Grandmont–Rosedale, MI",
    "Jefferson-Chalmers, MI",
    "Mexicantown, MI",
    "Hamtramck, MI",
    "Highland Park, MI",
    "Brightmoor, MI",
    "Bagley, MI",
    "Old Redford, MI",
    "East English Village, MI",
    "The Villages, MI",
    "Martin Park, MI",
    "Warrendale, MI",

    # Surrounding Areas
    "Dearborn, MI",
    "Southfield, MI",
    "Warren, MI",
    "Livonia, MI",
    "Redford, MI",
    "Royal Oak, MI",
    "Ferndale, MI",
    "Oak Park, MI",
    "Hazel Park, MI",
    "Berkley, MI",
    "Clawson, MI",
    "Troy, MI",
    "Madison Heights, MI",
    "St. Clair Shores, MI",
    "Grosse Pointe, MI",
    "Grosse Pointe Park, MI",
    "Grosse Pointe Farms, MI",
    "Grosse Pointe Woods, MI",
    "Grosse Pointe Shores, MI",
    "Eastpointe, MI",
    "Harper Woods, MI",
    "Farmington Hills, MI",
    "West Bloomfield, MI",
    "Bloomfield Hills, MI",
    "Novi, MI",
    "Canton, MI",
    "Plymouth, MI"
]

PHILADELPHIA_REGION = [
    # Central Philadelphia (Neighborhoods)
    "Center City, PA",
    "Old City, PA",
    "Rittenhouse Square, PA",
    "Society Hill, PA",
    "Chinatown, PA",
    "Queen Village, PA",
    "Bella Vista, PA",
    "Graduate Hospital, PA",
    "Fairmount, PA",
    "Logan Square, PA",
    "South Street, PA",
    "Washington Square West, PA",
    "Northern Liberties, PA",
    "Fishtown, PA",
    "Kensington, PA",
    "University City, PA",
    "West Philadelphia, PA",
    "East Falls, PA",
    "Roxborough, PA",
    "Manayunk, PA",
    "Chestnut Hill, PA",
    "Mount Airy, PA",
    "Germantown, PA",
    "Port Richmond, PA",
    "North Philadelphia, PA",
    "South Philadelphia, PA",
    "Northeast Philadelphia, PA",

    # Surrounding Areas
    "Bala Cynwyd, PA",
    "Ardmore, PA",
    "Upper Darby, PA",
    "Haverford, PA",
    "Bryn Mawr, PA",
    "Lansdowne, PA",
    "Narberth, PA",
    "Conshohocken, PA",
    "Jenkintown, PA",
    "Cheltenham, PA",
    "Glenside, PA",
    "Abington, PA",
    "Willow Grove, PA",
    "King of Prussia, PA",
    "Norristown, PA",
    "Plymouth Meeting, PA",
    "Bensalem, PA",
    "Feasterville-Trevose, PA",
    "Huntingdon Valley, PA",
    "Yeadon, PA",
    "Darby, PA",
    "Springfield, PA",
    "Media, PA",
    "Swarthmore, PA",
    "Newtown Square, PA",
    "Wayne, PA",
    "Havertown, PA"
]